DAB_PrefabRandomizerConfig {
 m_configName "TableOld_01_R01"
 m_replacementEntries {
  DAB_PrefabRandomizerConfigEntry "{6970D5C843630389}" {
   m_replacedPrefabs {
    "{2DB729170DBCE7BE}Prefabs/Props/Furniture/TableOld_01/TableOld_01.et"
    "{7FFE600A194D73B1}Prefabs/Props/Furniture/TableOld_01/TableOld_01_Base.et"
    "{40235C78B4D96949}Prefabs/Props/Furniture/TableOld_01/TableOld_01_brown.et"
    "{8FB2845D48F4E02A}Prefabs/Props/Furniture/TableOld_01/TableOld_01_white.et"
    "{77787EE24EC156F0}PrefabLibrary/DefaultLibrary/Props/Civilian/TableOld_01/TableOld_01.et"
    "{54CE51ABCAEF05C0}PrefabLibrary/DefaultLibrary/Props/Civilian/TableOld_01/TableOld_01_white.et"
   }
   m_replacerPrefabs {
    "{C0635192F7FA1E96}Prefabs/Props/Furniture/TableOld_01/TableOld_01_R01.et"
    "{AC3765724B3E91B8}Prefabs/Props/Furniture/TableOld_01/TableOld_01_R02.et"
    "{49AB298B47DB06D3}Prefabs/Props/Furniture/TableOld_01/TableOld_01_R03.et"
    "{749F0CB332B78FE4}Prefabs/Props/Furniture/TableOld_01/TableOld_01_R04.et"
   }
  }
 }
}